version: 2.1
jobs:
  compile:
   docker:
      - image: xyzuan/xdocker:latest
   steps:
      - run:
          command: |
            git clone --depth=1 https://github.com/Tiktodz/android_kernel_asus_sdm636.git -b lv kernel && cd kernel
            curl https://raw.githubusercontent.com/wizardprjkt/Kernel_Builder_CI_LV_S/main/build.sh > run.sh
            source run.sh
          no_output_timeout : 5h
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile 
      
