version: 2.1
jobs:
  compile:
   docker:
      - image: xyzuan/xdocker:latest
   steps:
      - run:
          command: |
            git clone --depth=1 https://github.com/Daffa06/NoName-X00T -b NLV-4.4-R43 kernel && cd kernel
            wget https://github.com/aslenofarid/Kernel_Builder_CI_LV_S/raw/LV-S/build.sh
            source build.sh
          no_output_timeout : 5h
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile 
