version: 2.1
jobs:
  compile:
   docker:
      - image: xyzuan/xdocker:latest
   steps:
      - run:
          command: |
            git clone --depth=1 https://github.com/aslenofarid/android_kernel_asus_sdm660.git -b lineage-17.1 kernel
            source kernel/build.sh
          no_output_timeout : 5h
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile 
      
